apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php74base
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php74base
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
