apiVersion: v1
kind: Service
metadata:
    name: php74base
    labels:
      app: php74base
spec:
    selector:
        app: php74base
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
