apiVersion: v1
kind: Service
metadata:
    name: php8.0-base
    labels:
      app: php8.0-base
spec:
    selector:
        app: php8.0-base
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
