apiVersion: v1
kind: Service
metadata:
    name: nginxfpmphp80base
    labels:
      app: nginxfpmphp80base
spec:
    selector:
        app: nginxfpmphp80base
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
